#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:$APPDIR/lib/gwt/gwt-user.jar:$APPDIR/lib/gwt/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.surelogic.sierra.gwt.SierraPortal;
