#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/nathan/gwt-linux-1.4.61/gwt-user.jar:/home/nathan/gwt-linux-1.4.61/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.surelogic.sierra.gwt.SierraPortal/SierraPortal.html;
