//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.05 at 02:09:56 PM EST 
//
package com.surelogic.sierra.tool.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArtifactType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ArtifactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mnemonic" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tool" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtifactType")
public class ArtifactType {
    @XmlAttribute(required = true)
    protected String mnemonic;
    @XmlAttribute(required = true)
    protected String tool;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the mnemonic property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMnemonic() {
        return mnemonic;
    }

    /**
     * Sets the value of the mnemonic property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMnemonic(String value) {
        this.mnemonic = value;
    }

    /**
     * Gets the value of the tool property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTool() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTool(String value) {
        this.tool = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }
}
