//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.14 at 04:39:55 PM EST 
//


package com.surelogic.sierra.tool.message;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>
 * Java class for Importance.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;Importance&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;IRRELEVANT&quot;/&gt;
 *     &lt;enumeration value=&quot;LOW&quot;/&gt;
 *     &lt;enumeration value=&quot;MEDIUM&quot;/&gt;
 *     &lt;enumeration value=&quot;HIGH&quot;/&gt;
 *     &lt;enumeration value=&quot;CRITICAL&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum
public enum Importance {

	IRRELEVANT, LOW, MEDIUM, HIGH, CRITICAL;

	public String value() {
		return name();
	}

	public static Importance fromValue(String v) {
		return valueOf(v.toUpperCase());
	}

	public String toStringSentenceCase() {
		return toString().substring(0, 1)
				+ toString().toLowerCase().substring(1);
	}

}
