//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.21 at 03:25:39 PM EDT 
//


package com.surelogic.sierra.tool.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.surelogic.sierra.tool.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Settings_QNAME = new QName("http://www.surelogic.com/sierra/1.0", "settings");
    private final static QName _FindingTypes_QNAME = new QName("http://www.surelogic.com/sierra/1.0", "findingTypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.surelogic.sierra.tool.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindingType }
     * 
     */
    public FindingType createFindingType() {
        return new FindingType();
    }

    /**
     * Create an instance of {@link FindingTypes }
     * 
     */
    public FindingTypes createFindingTypes() {
        return new FindingTypes();
    }

    /**
     * Create an instance of {@link FindingTypeFilter }
     * 
     */
    public FindingTypeFilter createFindingTypeFilter() {
        return new FindingTypeFilter();
    }

    /**
     * Create an instance of {@link ArtifactType }
     * 
     */
    public ArtifactType createArtifactType() {
        return new ArtifactType();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Settings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.surelogic.com/sierra/1.0", name = "settings")
    public JAXBElement<Settings> createSettings(Settings value) {
        return new JAXBElement<Settings>(_Settings_QNAME, Settings.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindingTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.surelogic.com/sierra/1.0", name = "findingTypes")
    public JAXBElement<FindingTypes> createFindingTypes(FindingTypes value) {
        return new JAXBElement<FindingTypes>(_FindingTypes_QNAME, FindingTypes.class, null, value);
    }

}
