CREATE TABLE SERVER_DEFINITION_RELTN (
  DEFINITION_UUID CHAR(36) NOT NULL PRIMARY KEY,
  SERVER_UUID CHAR(36) NOT NULL
)
<<>>
CREATE INDEX SD_SERVER_INDEX ON SERVER_DEFINITION_RELTN(SERVER_UUID)
<<>>
