CREATE TABLE DASHBOARD_SETTINGS (
  USER_ID              BIGINT         NOT NULL CONSTRAINT DASHBOARD_SETTINGS_USER_FK REFERENCES SIERRA_USER (ID),
  ROW_NUM              INTEGER        NOT NULL,
  COL_NUM              INTEGER        NOT NULL,
  REPORT_SETTINGS_UUID CHAR(36)       NOT NULL,
  OUTPUT_TYPE          INTEGER        NOT NULL,
  PRIMARY KEY (USER_ID,ROW_NUM,COL_NUM)
)
<<>>