DROP TABLE EMAIL
<<>>
RENAME COLUMN NOTIFICATION.EMAIL TO TO_EMAIL
<<>>
ALTER TABLE NOTIFICATION ADD COLUMN SMTP_HOST VARCHAR(32672)
<<>>
ALTER TABLE NOTIFICATION ADD COLUMN SMTP_PORT INTEGER
<<>>
ALTER TABLE NOTIFICATION ADD COLUMN SMTP_PASS VARCHAR(32672)
<<>>
ALTER TABLE NOTIFICATION ADD COLUMN SMTP_USER VARCHAR(32672)
<<>>
ALTER TABLE NOTIFICATION ADD COLUMN FROM_EMAIL VARCHAR(320)
<<>>
