
CREATE TABLE FILTER_SET (
  ID   BIGINT         NOT NULL PRIMARY KEY,
  UUID CHAR(36)       UNIQUE NOT NULL,
  NAME VARCHAR(32672) NOT NULL,
  INFO VARCHAR(32672)
)

<<>>

CREATE TABLE FILTER_SET_RELTN (
  CHILD_ID  BIGINT NOT NULL CONSTRAINT CHILD_FILTER_SET_FK REFERENCES FILTER_SET (ID),
  PARENT_ID BIGINT NOT NULL CONSTRAINT PARENT_FILTER_SET_FK REFERENCES FILTER_SET (ID),
  PRIMARY KEY (CHILD_ID,PARENT_ID)
)

<<>>

CREATE TABLE FILTER_ENTRY (
  FILTER_SET_ID   BIGINT NOT NULL CONSTRAINT FE_FILTER_SET_FK REFERENCES FILTER_SET (ID) ON DELETE CASCADE,
  FINDING_TYPE_ID BIGINT NOT NULL CONSTRAINT FE_FINDING_TYPE_FK REFERENCES FINDING_TYPE (ID),
  FILTERED        CHAR(1) NOT NULL CONSTRAINT FE_FILTERED_CN (CHECK (FILTERED IN ('Y','N')),
  PRIMARY KEY (FILTER_SET_ID,FINDING_TYPE_ID)
);

<<>>