
CREATE TABLE SCAN_SUMMARY (
  SCAN_ID            BIGINT NOT NULL CONSTRAINT SUMMARY_SCAN_FK REFERENCES SCAN (ID) ON DELETE CASCADE,
  QUALIFIER_ID       BIGINT NOT NULL CONSTRAINT SUMMARY_QUALIFIER_FK REFERENCES QUALIFIER (ID) ON DELETE CASCADE,
  NEW_FINDINGS       BIGINT NOT NULL,
  FIXED_FINDINGS     BIGINT NOT NULL,
  UNCHANGED_FINDINGS BIGINT NOT NULL,
  TOTAL_FINDINGS     BIGINT NOT NULL,
  ARTIFACT_COUNT     BIGINT NOT NULL,
  PRIMARY KEY (SCAN_ID,QUALIFIER_ID)
)

<<>>
