DROP TABLE FILTER_SET_FILTERS
<<>>
ALTER TABLE SETTING_FILTERS DROP COLUMN DELTA
<<>>
ALTER TABLE SETTING_FILTER_SETS ADD COLUMN IMPORTANCE INTEGER
<<>>
ALTER TABLE SETTING_FILTER_SETS ADD COLUMN FILTERED CHAR(1) NOT NULL DEFAULT 'N' CONSTRAINT SF_FILTERED_CN CHECK (FILTERED IN ('Y','N'))
<<>>