
CREATE TABLE DEFINITION (
  UUID        CHAR(36) NOT NULL PRIMARY KEY,
  DEF_TYPE    VARCHAR(2000) NOT NULL,
  REVISION    BIGINT,
  SERVER_UUID CHAR(36) CONSTRAINT DEFINITION_SERVERS_FK REFERENCES SERVERS (UUID)
)
<<>>

CREATE INDEX DEFINITION_TYPE_INDEX ON DEFINITION (DEF_TYPE)
<<>>