DROP INDEX A_N_R_PARENT_NUMBER_IDX
<<>>
DROP INDEX A_N_R_CHILD_NUMBER_IDX
<<>>
DROP TABLE ARTIFACT_NUMBER_RELTN
<<>>
CREATE TABLE ARTIFACT_NUMBER_RELTN (
  SCAN_ID       BIGINT NOT NULL CONSTRAINT ART_NUMBER_SCAN_FK REFERENCES SCAN (ID) ON DELETE CASCADE,
  PARENT_NUMBER INT NOT NULL,
  CHILD_NUMBER  INT NOT NULL,
  RELATION_TYPE VARCHAR(255) NOT NULL,
  PRIMARY KEY (SCAN_ID,CHILD_NUMBER,PARENT_NUMBER,RELATION_TYPE)
)
<<>>
CREATE INDEX A_N_R_PARENT_NUMBER_IDX ON ARTIFACT_NUMBER_RELTN (PARENT_NUMBER)
<<>>
CREATE INDEX A_N_R_CHILD_NUMBER_IDX ON ARTIFACT_NUMBER_RELTN (CHILD_NUMBER)
<<>>
CREATE INDEX A_N_R_RELATION_TYPE_IDX ON ARTIFACT_NUMBER_RELTN (RELATION_TYPE)
<<>>