ALTER TABLE FINDINGS_OVERVIEW DROP COLUMN FINDING_TYPE
<<>>
ALTER TABLE FINDINGS_OVERVIEW ADD COLUMN FINDING_TYPE VARCHAR(32672) CONSTRAINT F_O_FINDING_TYPE_FK REFERENCES FINDING_TYPE (UUID)
<<>>
DELETE FROM FINDINGS_OVERVIEW
<<>>