ALTER TABLE SERVER_LOCATION_PROJECT DROP CONSTRAINT SLP_SERVER_FK
<<>>
ALTER TABLE SERVER_LOCATION_PROJECT ADD CONSTRAINT SLP_SERVER_FK FOREIGN KEY (SERVER_ID) REFERENCES SERVER_LOCATION (ID) ON DELETE CASCADE
<<>>