DROP VIEW OLDEST_SCANS
<<>>
DROP VIEW LATEST_SCANS
<<>>

-- Displays the latest scan for each project/qualifier pair in the database.
CREATE VIEW LATEST_SCANS
  (QUALIFIER,PROJECT,SCAN_ID,SCAN_UUID,TIME)
AS SELECT 
   Q.NAME, P.NAME , R.ID, R.UUID, TIMES.TIME 
FROM QUALIFIER Q, SCAN R, PROJECT P,
   (
    SELECT QSR.QUALIFIER_ID AS QUALIFIER_ID,MAX(R2.SCAN_DATE_TIME) AS TIME
    FROM
        SCAN R2,
        QUALIFIER_SCAN_RELTN QSR,
        PROJECT P2
    WHERE
    	QSR.SCAN_ID = R2.ID AND
	R2.STATUS = 'FINISHED' AND
        P2.ID = R2.PROJECT_ID
    GROUP BY
        QSR.QUALIFIER_ID, P2.ID
   ) AS TIMES
WHERE R.SCAN_DATE_TIME = TIMES.TIME AND R.STATUS = 'FINISHED' AND P.ID = R.PROJECT_ID AND Q.ID = TIMES.QUALIFIER_ID
<<>>

--Displays the oldest scan for each project in the database, as long as it isn't also the newest scan.
CREATE VIEW OLDEST_SCANS
  (QUALIFIER,PROJECT,SCAN_ID,SCAN_UUID,TIME)
AS SELECT 
   Q.NAME, P.NAME , R.ID, R.UUID, TIMES.TIME 
FROM QUALIFIER Q, SCAN R, PROJECT P,
   (
    SELECT QSR.QUALIFIER_ID AS QUALIFIER_ID,MIN(R2.SCAN_DATE_TIME) AS TIME
    FROM
        SCAN R2,
        QUALIFIER_SCAN_RELTN QSR,
        PROJECT P2
    WHERE
    	QSR.SCAN_ID = R2.ID AND
	R2.STATUS = 'FINISHED' AND
        P2.ID = R2.PROJECT_ID
    GROUP BY
        QSR.QUALIFIER_ID, P2.ID
   ) AS TIMES
WHERE R.SCAN_DATE_TIME = TIMES.TIME AND R.STATUS = 'FINISHED' AND P.ID = R.PROJECT_ID AND Q.ID = TIMES.QUALIFIER_ID AND R.ID NOT IN (SELECT SCAN_ID FROM LATEST_SCANS)
<<>>
