CREATE TABLE ARTIFACT_ARTIFACT_RELTN (
  CHILD_ID  BIGINT NOT NULL CONSTRAINT AAR_CHILD_FK REFERENCES ARTIFACT (ID),
  PARENT_ID BIGINT NOT NULL CONSTRAINT AAR_PARENT_FK REFERENCES ARTIFACT (ID),
  PRIMARY KEY (CHILD_ID,PARENT_ID)
)
<<>>