
CREATE TABLE SERVER_LOCATION (
  ID           BIGINT        NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  LABEL        VARCHAR(255),
  PROTOCOL     VARCHAR(5)    NOT NULL CONSTRAINT SL_PROTOCOL_CN CHECK (PROTOCOL IN ('http','https')),
  HOST         VARCHAR(2000),
  PORT         INT,
  CONTEXT_PATH VARCHAR(2000),
  SERVER_USER  VARCHAR(255)
)
<<>>
CREATE TABLE DELETED_DEFINITIONS (
 DEFINITION_UUID CHAR(36)     UNIQUE NOT NULL CONSTRAINT DD_DEFINITION_UUID_FK REFERENCES SERVER_DEFINITION_RELTN(DEFINITION_UUID),
 SERVER_UUID     CHAR(36)     NOT NULL,
 REVISION        BIGINT       NOT NULL,
 DEFINITION_TYPE VARCHAR(10)  NOT NULL CONSTRAINT DD_TYPE_CN CHECK (DEFINITION_TYPE IN ('CATEGORY','FINDINGTYPE','SCANFILTER'))
)
<<>>
