UPDATE DASHBOARD_SETTINGS 
   SET REPORT_SETTINGS_UUID = (SELECT UUID FROM REPORT_SETTINGS WHERE REPORT_UUID = 'USERAUDITS') 
   WHERE REPORT_SETTINGS_UUID = (SELECT UUID FROM REPORT_SETTINGS WHERE REPORT_UUID = 'AUDITCONTRIBUTIONS')
<<>>
DELETE FROM REPORT_SETTINGS WHERE REPORT_UUID = 'AUDITCONTRIBUTIONS'
<<>>