INSERT INTO SERVER_DEFINITION_RELTN (SERVER_UUID, DEFINITION_UUID) 
   SELECT S.*, FS.* 
     FROM (SELECT UUID FROM FILTER_SET EXCEPT (SELECT DEFINITION_UUID FROM SERVER_DEFINITION_RELTN)) AS FS,
          SERVER S
<<>>
INSERT INTO SERVER_DEFINITION_RELTN (SERVER_UUID, DEFINITION_UUID) 
   SELECT SRV.*, S.* 
     FROM (SELECT UUID FROM SETTINGS WHERE UUID != 'de3034ec-65d5-4d4a-b059-1adf8fc7b12d' EXCEPT (SELECT DEFINITION_UUID FROM SERVER_DEFINITION_RELTN)) AS S,
          SERVER SRV
<<>>