ALTER TABLE SERVER_LOCATION ADD COLUMN UUID CHAR(36)
<<>>
ALTER TABLE SERVER_LOCATION ALTER LABEL NOT NULL
<<>>
ALTER TABLE SERVER_LOCATION ADD CONSTRAINT SERVER_LOCATION_LABEL_U_CN UNIQUE (LABEL)
<<>>