--This was never used in schema 2
DROP TABLE SYNCH
<<>>

CREATE TABLE SYNCH (
  PROJECT_ID        BIGINT NOT NULL CONSTRAINT SYNCH_PROJECT_FK REFERENCES PROJECT (ID),
  DATE_TIME         TIMESTAMP NOT NULL,
  COMMIT_REVISION   BIGINT NOT NULL,
  PRIOR_REVISION    BIGINT NOT NULL,
  PRIMARY KEY (PROJECT_ID,DATE_TIME)
)
<<>>
ALTER TABLE FINDINGS_OVERVIEW ADD COLUMN CATEGORY VARCHAR(32672)
<<>>
CREATE INDEX FO_CATEGORY_INDEX ON FINDINGS_OVERVIEW (CATEGORY)
<<>>