DROP TABLE ARTIFACT_ARTIFACT_RELTN
<<>>
ALTER TABLE ARTIFACT ADD COLUMN SCAN_NUMBER INT
<<>>
CREATE INDEX ARTIFACT_SCAN_NUMBER_IDX ON ARTIFACT (SCAN_NUMBER)
<<>>
CREATE TABLE ARTIFACT_NUMBER_RELTN (
  SCAN_ID       BIGINT NOT NULL CONSTRAINT ART_NUMBER_SCAN_FK REFERENCES SCAN (ID),
  PARENT_NUMBER INT NOT NULL,
  CHILD_NUMBER  INT NOT NULL,
  PRIMARY KEY (CHILD_NUMBER,PARENT_NUMBER)
)
<<>>
CREATE INDEX A_N_R_PARENT_NUMBER_IDX ON ARTIFACT_NUMBER_RELTN (PARENT_NUMBER)
<<>>
CREATE INDEX A_N_R_CHILD_NUMBER_IDX ON ARTIFACT_NUMBER_RELTN (CHILD_NUMBER)
<<>>