ALTER TABLE SETTING_FILTERS DROP CONSTRAINT SETTING_FILTERED_FK
<<>>
INSERT INTO SETTING_FILTERS (SETTINGS_ID,FINDING_TYPE_ID,FILTERED)
SELECT S.ID,FT.ID,'N'
FROM SETTINGS S, FINDING_TYPE FT 
WHERE S.UUID = 'de3034ec-65d5-4d4a-b059-1adf8fc7b12d' 
   AND FT.ID NOT IN 
    (SELECT FINDING_TYPE_ID 
     FROM SETTING_FILTERS SF
     WHERE SF.SETTINGS_ID = (SELECT MAX(ID) FROM SETTINGS WHERE UUID = 'de3034ec-65d5-4d4a-b059-1adf8fc7b12d'))
<<>>
DELETE FROM SETTING_FILTERS SF 
  WHERE  SF.SETTINGS_ID = (SELECT MAX(ID) FROM SETTINGS WHERE UUID = 'de3034ec-65d5-4d4a-b059-1adf8fc7b12d') AND SF.FILTERED = 'Y'
<<>>
UPDATE SETTING_FILTERS SET FILTERED = 'N' WHERE FILTERED IS NULL
<<>>
ALTER TABLE SETTING_FILTERS ADD CONSTRAINT SETTING_FILTERED_FK CHECK (FILTERED IN ('Y','N'))
<<>>