
CREATE TABLE SYNCH (
  PROJECT_ID        BIGINT NOT NULL CONSTRAINT SYNCH_PROJECT_FK REFERENCES PROJECT (ID),
  USER_ID           BIGINT NOT NULL CONSTRAINT SYNCH_USER_FK REFERENCES USER (ID),
  DATE_TIME         TIMESTAMP NOT NULL,
  COMMIT_REVISION   BIGINT NOT NULL,
  RECEIVED_REVISION BIGINT NOT NULL,
  PRIMARY KEY (PROJECT_ID,USER_ID,DATE_TIME)
);
<<>>