
DELETE FROM CATEGORY_FINDING_TYPE_RELTN
<<>>
DROP TABLE CATEGORY_FINDING_TYPE_RELTN
<<>>
ALTER TABLE FINDING_TYPE ADD COLUMN CATEGORY_ID BIGINT CONSTRAINT FT_FC_FK REFERENCES FINDING_CATEGORY (ID)
<<>>
DELETE FROM ART_TYPE_FIN_TYPE_RELTN
<<>>
DROP TABLE ART_TYPE_FIN_TYPE_RELTN
<<>>
ALTER TABLE ARTIFACT_TYPE ADD COLUMN FINDING_TYPE_ID BIGINT CONSTRAINT AT_FT_FK REFERENCES FINDING_TYPE (ID)
<<>>