
CREATE TABLE SYNCH (
  PROJECT_ID        BIGINT NOT NULL CONSTRAINT SYNCH_PROJECT_FK REFERENCES PROJECT (ID),
  USER_ID           BIGINT NOT NULL CONSTRAINT SYNCH_USER_FK REFERENCES SIERRA_USER (ID),
  DATE_TIME         TIMESTAMP NOT NULL,
  COMMIT_REVISION   BIGINT NOT NULL,
  RECEIVED_REVISION BIGINT NOT NULL,
  PRIMARY KEY (PROJECT_ID,USER_ID,DATE_TIME)
)
<<>>
ALTER TABLE SOURCE_LOCATION ADD COLUMN CLASS_NAME VARCHAR(32672)
<<>>
CREATE INDEX SL_CLASS_INDEX ON SOURCE_LOCATION (CLASS_NAME)
<<>>
ALTER TABLE COMPILATION_UNIT DROP CONSTRAINT COMPILATION_UNIT_CN
<<>>
RENAME COLUMN COMPILATION_UNIT.CLASS_NAME TO COMPILATION
<<>>
ALTER TABLE COMPILATION_UNIT ADD CONSTRAINT COMPILATION_UNIT_CN UNIQUE (PACKAGE_NAME,COMPILATION)
<<>>
ALTER TABLE SCAN_OVERVIEW ADD COLUMN COMPILATION VARCHAR(32672)
<<>>
ALTER TABLE FINDINGS_OVERVIEW ADD COLUMN COMPILATION VARCHAR (32672)
<<>>