CREATE TABLE TIME_SERIES_EVENT (
  ID             BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TIME_SERIES_ID BIGINT NOT NULL CONSTRAINT EVENT_TS_FK REFERENCES QUALIFIER (ID),
  NAME           VARCHAR(32672) NOT NULL,
  DATE_TIME      TIMESTAMP
  DESCRIPTION    VARCHAR(32672)
)
<<>>