CREATE TABLE REPORT_SETTINGS (
  UUID        CHAR(36)       NOT NULL PRIMARY KEY,
  USER_ID     BIGINT         NOT NULL CONSTRAINT REPORT_SETTINGS_USER_FK REFERENCES SIERRA_USER (ID),
  REPORT_UUID CHAR(36)       NOT NULL,
  TITLE       VARCHAR(32672),
  DESCRIPTION VARCHAR(32672)
)
<<>>
CREATE TABLE REPORT_SETTINGS_PARAM (
  REPORT_SETTINGS_UUID CHAR(36)       NOT NULL CONSTRAINT R_S_P_REPORT_SETTING_FK REFERENCES REPORT_SETTINGS (UUID) ON DELETE CASCADE,
  PARAM_NAME           VARCHAR(255)   NOT NULL,
  PARAM_VALUE          VARCHAR(32672) NOT NULL,
  ORDINAL              INT            NOT NULL,
  PRIMARY KEY (REPORT_SETTINGS_UUID,PARAM_NAME,ORDINAL)
)
<<>>
