CREATE TABLE SIERRA_GROUP (
  ID   NUMBER       NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) UNIQUE NOT NULL,
  INFO VARCHAR(2000)
)

<<>>

CREATE SEQUENCE SIERRA_GROUP_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
<<>>

CREATE TRIGGER SIERRA_GROUP_INC
BEFORE INSERT ON SIERRA_GROUP FOR EACH ROW
BEGIN
  SELECT SIERRA_GROUP_SEQ.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

<<>>

CREATE TABLE GROUP_USER_RELTN (
  GROUP_ID NUMBER NOT NULL CONSTRAINT G_U_R_GROUP_FK REFERENCES SIERRA_GROUP (ID) ON DELETE CASCADE,
  USER_ID  NUMBER NOT NULL CONSTRAINT G_U_R_USER_FK  REFERENCES SIERRA_USER (ID) ON DELETE CASCADE,
  PRIMARY KEY (GROUP_ID, USER_ID)
)
<<>>


