
CREATE TABLE SETTING_FILTER_SETS (
  SETTINGS_ID   NUMBER NOT NULL CONSTRAINT PFS_SETTING_FK REFERENCES SETTINGS (ID) ON DELETE CASCADE,
  FILTER_SET_ID NUMBER NOT NULL CONSTRAINT PFS_FILTER_SET_FK REFERENCES FILTER_SET (ID) ON DELETE CASCADE
)

<<>>