
CREATE TABLE SCAN_SUMMARY (
  SCAN_ID            NUMBER NOT NULL CONSTRAINT SUMMARY_SCAN_FK REFERENCES SCAN (ID) ON DELETE CASCADE,
  QUALIFIER_ID       NUMBER NOT NULL CONSTRAINT SUMMARY_QUALIFIER_FK REFERENCES QUALIFIER (ID) ON DELETE CASCADE,
  NEW_FINDINGS       NUMBER NOT NULL,
  FIXED_FINDINGS     NUMBER NOT NULL,
  UNCHANGED_FINDINGS NUMBER NOT NULL,
  TOTAL_FINDINGS     NUMBER NOT NULL,
  ARTIFACT_COUNT     NUMBER NOT NULL,
  PRIMARY KEY (SCAN_ID,QUALIFIER_ID)
)
<<>>