
DROP TABLE SYNCH
<<>>

CREATE TABLE COMMIT_AUDITS (
 PROJECT_ID NUMBER NOT NULL CONSTRAINT COMMIT_AUDITS_PROJECT_FK REFERENCES PROJECT (ID),
 USER_ID    NUMBER NOT NULL CONSTRAINT COMMIT_AUDITS_USER_FK REFERENCES SIERRA_USER (ID),
 REVISION   NUMBER NOT NULL CONSTRAINT COMMIT_AUDITS_REVISION_FK REFERENCES REVISION (ID),
 PRIMARY KEY (PROJECT_ID,USER_ID,COMMIT_REVISION)
)
<<>>

CREATE INDEX AUDIT_REVISION_INDEX ON SIERRA_AUDIT (REVISION)
<<>>