CREATE TABLE SERVER_DEFINITION_RELTN (
  DEFINITION_UUID UNIQUE NOT NULL CHAR(36),
  SERVER_UUID     NOT NULL CHAR(36),
  PRIMARY KEY (DEFINITION_UUID,SERVER_UUID)
)
<<>>
CREATE INDEX SD_DEFINITION_INDEX ON SERVER_DEFINITION_RELTN(DEFINITION_UUID)
<<>>
CREATE INDEX SD_SERVER_INDEX ON SERVER_DEFINITION_RELTN(SERVER_UUID)
<<>>