CREATE TABLE TIME_SERIES_EVENT (
  ID             NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TIME_SERIES_ID NUMBER NOT NULL CONSTRAINT EVENT_TS_FK REFERENCES QUALIFIER (ID),
  NAME           VARCHAR(2000) NOT NULL,
  DATE_TIME      TIMESTAMP
  DESCRIPTION    VARCHAR(2000)
)
<<>>