
CREATE TABLE SYNCH (
  PROJECT_ID        NUMBER NOT NULL CONSTRAINT SYNCH_PROJECT_FK REFERENCES PROJECT (ID),
  USER_ID           NUMBER NOT NULL CONSTRAINT SYNCH_USER_FK REFERENCES SIERRA_USER (ID),
  DATE_TIME         TIMESTAMP NOT NULL,
  COMMIT_REVISION   NUMBER NOT NULL,
  RECEIVED_REVISION NUMBER NOT NULL,
  PRIMARY KEY (PROJECT_ID,USER_ID,DATE_TIME)
)
<<>>
ALTER TABLE SOURCE_LOCATION ADD CLASS_NAME VARCHAR(2000)
<<>>
CREATE INDEX SL_CLASS_INDEX ON SOURCE_LOCATION (CLASS_NAME)
<<>>
ALTER TABLE COMPILATION_UNIT DROP CONSTRAINT COMPILATION_UNIT_CN
<<>>
ALTER TABLE COMPILATION_UNIT RENAME COLUMN CLASS_NAME TO CU
<<>>
ALTER TABLE COMPILATION_UNIT ADD CONSTRAINT COMPILATION_UNIT_CN UNIQUE (PACKAGE_NAME,CU)
<<>>
ALTER TABLE SCAN_OVERVIEW ADD CU VARCHAR(2000)
<<>>
ALTER TABLE FINDINGS_OVERVIEW ADD CU VARCHAR (2000)
<<>>
