

--
-- Eclipse Client Views
--
-- The Eclipse Client uses theses views for its presentation of results

CREATE VIEW PROJECT_OVERVIEW
  (PROJECT)
AS SELECT NAME FROM PROJECT;

CREATE VIEW LATEST_SCANS
  (PROJECT,SCAN_ID,TIME)
AS SELECT 
   P.NAME "PROJECT", R.ID "SCAN_ID", TIMES.TIME 
FROM SCAN R, PROJECT P,
   (
    SELECT MAX(R2.SCAN_DATE_TIME) AS TIME
    FROM
        SCAN R2,
        PROJECT P2
    WHERE
        P2.ID = R2.PROJECT_ID
    GROUP BY
        P2.NAME
   ) AS TIMES
WHERE R.SCAN_DATE_TIME = TIMES.TIME AND P.ID = R.PROJECT_ID;



CREATE VIEW FINDINGS_OVERVIEW
   (PROJECT,PACKAGE_NAME,CLASS_NAME,LOC,SUMMARY,IS_READ,IMPORTANCE_CODE,IMPORTANCE,TOOL,CATEGORY,MNEMONIC,FINDING_ID)
AS SELECT
   LR.PROJECT, CU.PACKAGE_NAME, CU.CLASS_NAME, S.LINE_OF_CODE, A.MESSAGE, F.IS_READ, F.IMPORTANCE,
   case
     when F.IMPORTANCE=0 then 'Irrelevant'
     when F.IMPORTANCE=1 then 'Low'
     when F.IMPORTANCE=2 then 'Medium'
     when F.IMPORTANCE=3 then 'High'
     when F.IMPORTANCE=4 then 'Critical'
   end,
   T.NAME, FT.CATEGORY, FT.MNEMONIC_DISPLAY,F.ID
FROM
   LATEST_SCANS LR,
   ARTIFACT A,
   ARTIFACT_FINDING_RELTN AFR,
   FINDING F,
   FINDING_TYPE FT,
   TOOL T,
   SOURCE_LOCATION S,
   COMPILATION_UNIT CU
WHERE
   A.SCAN_ID = LR.SCAN_ID AND
   AFR.ARTIFACT_ID = A.ID AND
   S.ID = A.PRIMARY_SOURCE_LOCATION_ID AND
   CU.ID = S.COMPILATION_UNIT_ID AND
   F.ID = AFR.FINDING_ID AND
   FT.ID = A.FINDING_TYPE_ID AND
   T.ID = FT.TOOL_ID;

ALTER TABLE COMPILATION_UNIT DROP CONSTRAINT COMPILATION_UNIT_CN;
ALTER TABLE COMPILATION_UNIT DROP COLUMN PATH;
ALTER TABLE COMPILATION_UNIT DROP COLUMN COUNT;
ALTER TABLE COMPILATION_UNIT ADD CONSTRAINT COMPILATION_UNIT_CN UNIQUE (PACKAGE_NAME, CLASS_NAME);