
CREATE TABLE PRODUCT (
  ID             BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME           VARCHAR(32672)  UNIQUE NOT NULL
);

CREATE TABLE PRODUCT_PROJECT_RELTN (
  PRODUCT_ID     BIGINT       NOT NULL CONSTRAINT PPR_PRODUCT_FK REFERENCES PRODUCT (ID),
  PROJECT_ID     BIGINT       NOT NULL CONSTRAINT PPR_PROJECT_FK REFERENCES PROJECT (ID),
  PRIMARY KEY (PRODUCT_ID,PROJECT_ID)
);


CREATE TABLE QUALIFIER (
  ID             BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME           VARCHAR(32672) UNIQUE NOT NULL
);

INSERT INTO QUALIFIER (NAME) VALUES ('Default');

CREATE TABLE QUALIFIER_RUN_RELTN (
  QUALIFIER_ID   BIGINT        NOT NULL CONSTRAINT QUALIFIER_RUN_QUALIFIER_FK REFERENCES QUALIFIER (ID),
  RUN_ID         BIGINT        UNIQUE NOT NULL CONSTRAINT QUALIFIER_RUN_RUN_FK REFERENCES RUN (ID),
  PRIMARY KEY (QUALIFIER_ID,RUN_ID)
);

ALTER TABLE FINDING ADD COLUMN QUALIFIER_ID BIGINT NOT NULL CONSTRAINT QUALIFIER_FINDING_QUALIFIER_FK REFERENCES QUALIFIER (ID);

ALTER TABLE TRAIL ADD COLUMN QUALIFIER_ID BIGINT NOT NULL CONSTRAINT QUALIFIER_FINDING_QUALIFIER_FK REFERENCES QUALIFIER (ID); 

ALTER TABLE SIERRA_MATCH ADD COLUMN QUALIFIER_ID BIGINT NOT NULL CONSTRAINT QUALIFIER_FINDING_QUALIFIER_FK REFERENCES QUALIFIER (ID);
ALTER TABLE SIERRA_MATCH DROP PRIMARY KEY;
ALTER TABLE SIERRA_MATCH ADD PRIMARY KEY (PROJECT_ID,HASH, PACKAGE_NAME, CLASS_NAME, FINDING_TYPE_ID, QUALIFIER_ID)
