
CREATE TABLE PRODUCT (
  ID             BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME           VARCHAR(32672)  UNIQUE NOT NULL
);

CREATE TABLE PRODUCT_PROJECT_RELTN (
  PRODUCT_ID     BIGINT       NOT NULL CONSTRAINT PPR_PRODUCT_FK REFERENCES PRODUCT (ID) ON DELETE CASCADE,
  PROJECT_NAME   VARCHAR(32672)	NOT NULL CONSTRAINT PPR_PROJECT_FK REFERENCES PROJECT (NAME),
  PRIMARY KEY (PRODUCT_ID,PROJECT_NAME)
);

CREATE TABLE QUALIFIER (
  ID             BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME           VARCHAR(32672) UNIQUE NOT NULL
);

CREATE TABLE QUALIFIER_SCAN_RELTN (
  QUALIFIER_ID   BIGINT        NOT NULL CONSTRAINT QUALIFIER_SCAN_QUALIFIER_FK REFERENCES QUALIFIER (ID),
  SCAN_ID         BIGINT        UNIQUE NOT NULL CONSTRAINT QUALIFIER_SCAN_SCAN_FK REFERENCES SCAN (ID) ON DELETE CASCADE,
  PRIMARY KEY (QUALIFIER_ID,SCAN_ID)
);

CREATE TABLE REVISION (
  REVISION           BIGINT             NOT NULL
);

INSERT INTO REVISION (REVISION) VALUES (0);

CREATE TABLE SETTINGS (
  NAME           VARCHAR(255)  PRIMARY KEY NOT NULL,
  REVISION       BIGINT        NOT NULL,       
  SETTINGS       CLOB          NOT NULL,
  PRIMARY KEY (PROJECT_ID,REVISION)
);

ALTER TABLE PROJECT DROP COLUMN TEXT;
ALTER TABLE PROJECT DROP COLUMN REVISION
ALTER TABLE PROJECT ADD COLUMN SETTINGS_NAME  VARCHAR(255)  NOT NULL CONSTRAINT SETTINGS_FK REFERENCES SETTINGS (NAME);

