
CREATE TABLE PRODUCT (
  ID    BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME  VARCHAR(32672) UNIQUE NOT NULL
);

CREATE TABLE PRODUCT_PROJECT_RELTN (
  PRODUCT_ID    BIGINT       NOT NULL CONSTRAINT PPR_PRODUCT_FK REFERENCES PRODUCT(ID) ON DELETE CASCADE,
  PROJECT_NAME  VARCHAR(255) NOT NULL,
  PRIMARY KEY (PRODUCT_ID,PROJECT_NAME)
);

CREATE TABLE QUALIFIER (
  ID    BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME  VARCHAR(32672) UNIQUE NOT NULL
);

CREATE TABLE QUALIFIER_SCAN_RELTN (
  QUALIFIER_ID  BIGINT NOT NULL CONSTRAINT QUALIFIER_SCAN_QUALIFIER_FK REFERENCES QUALIFIER(ID),
  SCAN_ID       BIGINT UNIQUE NOT NULL CONSTRAINT QUALIFIER_SCAN_SCAN_FK REFERENCES SCAN(ID) ON DELETE CASCADE,
  PRIMARY KEY (QUALIFIER_ID,SCAN_ID)
);

CREATE TABLE REVISION (
  REVISION   BIGINT    NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATE_TIME  TIMESTAMP NOT NULL         
);

CREATE TABLE SETTINGS (
  NAME      VARCHAR(255) PRIMARY KEY NOT NULL,
  REVISION  BIGINT       NOT NULL,       
  SETTINGS  CLOB         NOT NULL
);

CREATE TABLE PROJECT_SETTINGS_RELTN (
  PROJECT_ID     BIGINT       UNIQUE NOT NULL CONSTRAINT PSR_PROJECT_FK REFERENCES PROJECT(ID),
  SETTINGS_NAME  VARCHAR(255) NOT NULL CONSTRAINT PSR_SETTINGS_FK REFERENCES SETTINGS(NAME),
  PRIMARY KEY (PROJECT_ID,SETTINGS_NAME)
);

ALTER TABLE PROJECT DROP COLUMN SETTINGS;
ALTER TABLE PROJECT DROP COLUMN SETTINGS_REVISION;

CREATE TABLE SERVER (
  UID  CHAR(36) NOT NULL PRIMARY KEY 
);

